name: Build App
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --prefer-binary -r requirements.txt
          pip install pyinstaller
          
      - name: Build executable
        run: |
          pyinstaller --clean --onefile --paths="${{ github.workspace }}" \
            --hidden-import=analyzer_enhanced \
            --add-data "analyzer_enhanced.py:." \
            --name "EnhancedDataAn" main.py
            
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: DataAn-Enhanced-Linux
          path: dist/EnhancedDataAn
          
      - name: Show PyInstaller warnings
        run: cat build/EnhancedDataAn/warn-EnhancedDataAn.txt

  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        # Убраны символы ` , так как каждая строка и так отдельная команда
        run: |
          python -m pip install --upgrade pip
          pip install --prefer-binary -r requirements.txt
          pip install pyinstaller
          
      - name: Build EXE
        # --paths=. и --hidden-import для фикса ошибки с модулем
        run: pyinstaller --clean --onefile --paths=. --hidden-import=analyzer_enhanced --add-data "analyzer_enhanced.py;." --name "EnhancedDataAn" --icon=icon.ico main.py        
        
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: DataAn-Enhanced-Windows
          path: dist/EnhancedDataAn.exe
